avijit-codeclouds/movie-app

- movie-server/controller/UserController.js
- movie-server/models/User.js
- movie-server/package-lock.json
- movie-server/package.json
- movie-server/routes/users.js
> user registration

- movie-server/app.js
- movie-server/controller/UserController.js
validation related to valid email done
> validation related to valid email done

- movie-server/controller/UserController.js
- movie-server/routes/users.js
> login done

- movie-server/app.js
- movie-server/config/checkauth.js
- movie-server/controller/Generecontroller.js
- movie-server/models/Genere.js
- movie-server/routes/genere.js
authentication with jwt and created genere
> authentication with jwt and created genere

- movie-server/controller/Generecontroller.js
- movie-server/controller/UserController.js
validation manage for no req done
> validation manage for no req done

- movie-client/src/app/app-routing.module.ts
- movie-client/src/app/app.component.html
- movie-client/src/app/app.component.ts
- movie-client/src/app/app.module.ts
- movie-client/src/app/customers/customers.component.ts
- movie-client/src/app/guards/auth.guard.spec.ts
- movie-client/src/app/guards/auth.guard.ts
- movie-client/src/app/guards/jwt.interceptor.ts
- movie-client/src/app/login/login.component.ts
- movie-client/src/app/logout/logout.component.html
- movie-client/src/app/logout/logout.component.spec.ts
- movie-client/src/app/logout/logout.component.ts
- movie-client/src/app/services/auth.service.ts
> login & register done

- movie-client/angular.json
- movie-client/src/index.html
> css added on json

- movie-client/src/app/login/login.component.html
> mat implemented

- movie-server/config/checkauth.js
- movie-server/controller/MovieController.js
- movie-server/models/Movie.js
- movie-server/routes/movie.js
- movie-server/validator/movieValidate.js
movie add,edit,list,single view
> movie add,edit,list,single view

- movie-server/routes/movie.js
> movie list api changed

- movie-client/package-lock.json
- movie-server/controller/MovieController.js
> produce result of movies

- movie-client/src/app/movies/movies.component.ts
> updated movie component

- movie-server/routes/genere.js
> removed auth from genre list

- movie-client/src/app/newmovie/newmovie.component.html
- movie-client/src/app/newmovie/newmovie.component.ts
- movie-client/src/app/services/movie.service.ts
> new movie add completed

- movie-client/src/app/app.module.ts
- movie-client/src/app/movies/movies.component.html
- movie-client/src/app/movies/movies.component.ts
> Fixed build issue

- movie-client/src/app/movies/movies.component.css
- movie-client/src/app/movies/movies.component.html
> working on movies update

- movie-client/src/app/app-routing.module.ts
> guard the access level

- movie-client/package-lock.json
- movie-client/package.json
- movie-client/src/app/movies/movies.component.html
- movie-client/src/app/movies/movies.component.ts
- movie-client/src/app/movies/movies.module.ts
- movie-client/src/app/services/gener.service.ts
- movie-client/src/app/services/movie.service.ts
pagination done in movie view and error handling in services
> pagination done in movie view and error handling in services

- movie-client/src/app/services/movie.service.ts
- movie-client/src/app/updatemovie/updatemovie.component.ts
> uodating movie edit file

- movie-client/src/app/movies/movies.component.ts
> build issue fixed

- movie-client/src/app/login/login.component.html
- movie-client/src/app/login/login.component.ts
- movie-client/src/app/newmovie/newmovie.component.html
- movie-client/src/app/newmovie/newmovie.component.ts
- movie-client/src/app/register/register.component.html
- movie-client/src/app/register/register.component.ts
- movie-client/src/app/updatemovie/updatemovie.component.html
- movie-client/src/app/updatemovie/updatemovie.component.ts
progress bar and update movie added
> progress bar and update movie added

- movie-client/src/app/movies/movies.component.html
> bug fixing done

- movie-client/package-lock.json
- movie-client/package.json
- movie-client/src/app/movies/movies.component.html
- movie-client/src/app/movies/movies.component.ts
- movie-client/src/app/movies/movies.module.ts
> side bar fixing

- movie-client/src/app/services/auth.service.ts
- movie-client/src/app/services/gener.service.ts
> error alert removed

- movie-client/src/app/movies/movies.component.html
> svg icon implemented

- movie-server/controller/MovieController.js
- movie-server/models/Wishlist.js
- movie-server/routes/movie.js
- movie-server/validator/movieValidate.js
> wishlist api created

- movie-server/app.js
- movie-server/config/winston.js
- movie-server/controller/MovieController.js
- movie-server/package-lock.json
- movie-server/package.json
> logger added

- movie-client/package-lock.json
- movie-client/package.json
- movie-client/src/app/movies/movies.component.html
- movie-client/src/app/movies/movies.component.ts
- movie-client/src/app/movies/movies.module.ts
toggle functionality for wishlist ,only toggling done
> toggle functionality for wishlist ,only toggling done

- movie-client/src/app/movies/movies-routing.module.ts
> added guard

- movie-client/src/app/movies/movies.component.html
- movie-client/src/app/movies/movies.component.ts
- movie-client/src/app/services/movie.service.ts
> checkbox added for wishlist

- movie-server/app.js
- movie-server/controller/RentController.js
- movie-server/models/Rent.js
- movie-server/package-lock.json
- movie-server/package.json
- movie-server/routes/rent.js
> working on rent services

- movie-server/config/checkauth.js
> auth bug fixed done

- movie-server/controller/RentController.js
- movie-server/package-lock.json
- movie-server/package.json
- movie-server/routes/wishlist.js
> new packages

- movie-server/controller/RentController.js
- movie-server/routes/rent.js
> rent pause

- movie-server/controller/RentController.js
- movie-server/models/Genere.js
- movie-server/models/Movie.js
- movie-server/models/Rent.js
- movie-server/models/User.js
- movie-server/routes/rent.js
- movie-server/validator/validate.js
> cencel rent

- movie-server/controller/MovieController.js
- movie-server/controller/RentController.js
- movie-server/routes/movie.js
> movie updated

- movie-client/src/app/app.module.ts
- movie-client/src/app/model/wishlist.spec.ts
- movie-client/src/app/model/wishlist.ts
- movie-client/src/app/movies/movies.component.html
- movie-client/src/app/movies/movies.component.ts
- movie-client/src/app/newmovie/newmovie.component.ts
- movie-client/src/app/services/gener.service.ts
- movie-client/src/app/services/movie.service.ts
- movie-client/src/app/updatemovie/updatemovie.component.ts
> generelist ui route fixed

- movie-server/controller/RentController.js
> response changed

- movie-server/controller/WishlistController.js
> wishlist updated

- movie-server/controller/MovieController.js
- movie-server/controller/RentController.js
- movie-server/doc.txt
- movie-server/routes/movie.js
- movie-server/routes/rent.js
> validation changed

- movie-server/controller/MovieController.js
- movie-server/controller/RentController.js
> remove package

- movie-client/src/app/movies/movies.component.ts
- movie-client/src/app/services/movie.service.ts
> wishlist frontend updated

- movie-client/src/app/movies/movies.component.html
- movie-client/src/app/movies/movies.component.ts
wishlist error related to when no wishlists exists
> wishlist error related to when no wishlists exists

- movie-server/controller/WishlistController.js
> status code changed

- movie-client/src/app/movies/movies.component.html
- movie-client/src/app/movies/movies.component.ts
- movie-client/src/app/newmovie/newmovie.component.html
- movie-client/src/app/newmovie/newmovie.component.ts
- movie-client/src/app/services/movie.service.ts
- movie-client/src/app/updatemovie/updatemovie.component.html
- movie-client/src/app/updatemovie/updatemovie.component.ts
movie add ,update delete based on user_id created and fixed
> movie add ,update delete based on user_id created and fixed

- movie-server/controller/MovieController.js
- movie-server/models/Movie.js
- movie-server/routes/movie.js
- movie-server/validator/validate.js
movie add,update and delete with user_id fixed and created
> movie add,update and delete with user_id fixed and created

- movie-client/src/app/movies/movies.component.ts
deleted row shown after deleted successfully movie fixed
> deleted row shown after deleted successfully movie fixed

- movie-server/controller/RentController.js
- movie-server/routes/rent.js
> rent changed

- movie-client/src/app/services/movie.service.ts
> sort by date movielist

- movie-server/controller/WishlistController.js
- movie-server/routes/wishlist.js
pending status response trying to fixed for wishlist
> pending status response trying to fixed for wishlist

- movie-server/app.js
- movie-server/controller/MovieController.js
- movie-server/controller/RentController.js
- movie-server/models/Rent.js
- movie-server/package-lock.json
- movie-server/package.json
- movie-server/routes/rent.js
> movie and rent changing

- movie-client/package-lock.json
- movie-client/package.json
- movie-client/src/app/login/login.component.ts
- movie-client/src/app/movies/movies.component.ts
> userid decoded from token

- movie-client/src/app/movies/movies.component.ts
bug fixed related to production build
> bug fixed related to production build

- movie-server/models/Rent.js
> model change

- movie-client/src/app/movies/movies.component.ts
fixed array to object movie id in wishlist
> fixed array to object movie id in wishlist

- movie-client/src/app/movies/movies.component.html
update form restricted from user
> update form restricted from user

- movie-client/src/app/movies/movies.component.html
- movie-client/src/app/movies/movies.component.ts
updated movie UI based on admin
> updated movie UI based on admin

- movie-client/src/app/movies/movies.component.html
> change class respetive icon

- movie-client/package-lock.json
- movie-client/src/app/movies/movies.component.html
- movie-client/src/app/movies/movies.component.ts
- movie-server/doc.txt
- movie-server/models/Rent.js
- movie-server/package-lock.json
- movie-server/package.json
> rent on movies

- movie-client/src/app/movies/movies.component.html
- movie-client/src/app/movies/movies.component.ts
- movie-client/src/app/movies/movies.module.ts
- movie-client/src/app/services/movie.service.ts
> movie on rent

- movie-client/src/app/app-routing.module.ts
- movie-client/src/app/app.component.html
- movie-client/src/app/app.module.ts
- movie-client/src/app/wishlist/wishlist.component.html
- movie-client/src/app/wishlist/wishlist.component.spec.ts
- movie-client/src/app/wishlist/wishlist.component.ts
wishlist component and routes created
> wishlist component and routes created

- movie-client/src/app/wishlist/wishlist.component.html
listing page deign fixed for fav movielist
> listing page deign fixed for fav movielist

- movie-client/package-lock.json
- movie-client/package.json
- movie-client/src/app/movies/movies.component.ts
- movie-server/package-lock.json
> updated rent UI

- movie-client/src/app/movies/movies.component.ts
checked id fixed in UI to show after refactoring
> checked id fixed in UI to show after refactoring

- movie-client/package-lock.json
- movie-server/app.js
- movie-server/package-lock.json
- movie-server/package.json
- movie-server/routes.js
> minor changes in server

- movie-server/app.js
> server changed

- movie-client/src/app/pages/login/login.component.ts
- movie-client/src/app/pages/movies/movies.component.html
- movie-client/src/app/pages/wishlist/wishlist.component.html
- movie-client/src/app/pages/wishlist/wishlist.component.ts
- movie-client/src/app/services/gener.service.ts
> trim whitespace fixed

- movie-client/src/app/pages/wishlist/wishlist.component.html
> rent added to favorites page

- movie-client/src/app/pages/wishlist/wishlist.component.html
> loader fixed

- movie-client/server.js
- movie-server/app.js
> server pages

- movie-server/models/Rent.js
- movie-server/models/Wishlist.js
> index added

- movie-client/src/app/pages/movies/movies.component.ts
- movie-client/src/app/pages/wishlist/wishlist.component.ts
snackbar alert for movie deletion from wishlist and added o wishlist
> snackbar alert for movie deletion from wishlist and added o wishlist

- movie-server/app.js
- movie-server/jobs/rendModifications.js
- movie-server/models/Rent.js
> Expiration cron job added

- movie-client/package-lock.json
- movie-server/routes/rent.js
> rent changing

- movie-server/app.js
- movie-server/jobs/rendModifications.js
- movie-server/models/Rent.js
> extension fix

- movie-client/src/app/pages/movies/movies.component.ts
> updated spelling fixed

- movie-client/src/app/app.component.html
- movie-client/src/app/pages/wishlist/wishlist.component.html
> wishlist page UI fixed header

- movie-client/src/app/pages/wishlist/wishlist.component.html
- movie-client/src/app/pages/wishlist/wishlist.component.ts
added a confirm box in case of wishlist deletion
> added a confirm box in case of wishlist deletion

- movie-server/jobs/rendModifications.js
modify Expire console message added
> modify Expire console message added

- movie-server/controller/RentController.js
account lock added in rent controller
> account lock added in rent controller

- movie-server/controller/RentController.js
- movie-server/jobs/index.js
> updated rent controller

- movie-client/src/app/pages/movies/movies.component.css
> check button updated

- .gitignore
- movie-client/.gitignore
- movie-client/package-lock.json
- package-lock.json
> gitignore changed

- movie-client/src/app/pages/movies/movies.component.html
- movie-client/src/app/pages/movies/movies.module.ts
- movie-client/src/app/pages/wishlist/wishlist.component.html
> using tooltip icon fixed

- movie-client/src/app/pages/wishlist/wishlist.component.html
Wishlist sorting by last element displaying first
> Wishlist sorting by last element displaying first

- movie-client/src/app/pages/wishlist/wishlist.component.html
- movie-client/src/app/pages/wishlist/wishlist.component.ts
No wishlist found written when no wishlist is there
> No wishlist found written when no wishlist is there

- movie-client/src/app/pages/rentals/rentals.component.html
- movie-client/src/app/pages/rentals/rentals.component.ts
> Dev - fixes rental issue

- movie-client/src/app/pages/wishlist/wishlist.component.html
> updated tooltip

- movie-client/src/app/pages/wishlist/wishlist.component.html
sorting wishlist fixed with build issue
> sorting wishlist fixed with build issue

- movie-client/package-lock.json
- movie-client/src/app/app.module.ts
- movie-client/src/app/pages/movies/movies.component.html
- movie-client/src/app/pages/movies/movies.component.ts
- movie-server/controller/MovieController.js
> delete movie server and UI

- movie-client/src/app/pages/wishlist/wishlist.component.html
- movie-client/src/app/pages/wishlist/wishlist.component.ts
table header fixed in wishlist
> table header fixed in wishlist

- movie-client/src/app/pages/movies/movies.module.ts
> progress bar on header

- movie-client/package-lock.json
- movie-server/package-lock.json
- movie-server/routes.js
- movie-server/swagger/swagger.json
> swagger on progress

- movie-server/jobs/rendModifications.js
Some modification in modifyExpire function
> Some modification in modifyExpire function

- movie-client/src/app/app.component.html
- movie-client/src/app/app.component.ts
header and username displayed done in cilent side
> header and username displayed done in cilent side

- movie-server/swagger/swagger.json
> swagger updated

- movie-client/src/app/pages/movies/movies.component.html
- movie-client/src/app/pages/movies/movies.component.ts
- movie-client/src/app/pages/wishlist/wishlist.component.html
- movie-client/src/app/pages/wishlist/wishlist.component.ts
pagination fixed with condition
> pagination fixed with condition

- movie-client/src/app/pages/login/login.component.ts
fixed token display into console
> fixed token display into console

- movie-server/jobs/rendModifications.js
- movie-server/models/Rent.js
commented code removed from model-->Rent & rentmodications.js
> commented code removed from model-->Rent & rentmodications.js

- movie-server/jobs/rendModifications.js
- movie-server/models/Rent.js
This reverts commit 56199d3e1ae8264393b781bbed8fd83d697008bf, reversing
changes made to 670a04cf0027c0b842f0a8cd3ea35f0d5cd72f71.
> Revert "Merge pull request #178 from avijit-codeclouds/development"

- movie-server/jobs/rendModifications.js
- movie-server/models/Rent.js
Commented lines removed from code
> Commented lines removed from code

- movie-client/src/app/services/movie.service.ts
movie list sort by createdAt fixed
> movie list sort by createdAt fixed

- movie-client/src/app/pages/wishlist/wishlist.component.html
- movie-client/src/app/pages/wishlist/wishlist.component.ts
wishlist updated with pagination conditions including no wishlist found
> wishlist updated with pagination conditions including no wishlist found

- movie-client/package-lock.json
- movie-server/controller/RentController.js
- movie-server/models/Rent.js
- movie-server/package-lock.json
> rent issues

- movie-server/controller/RentController.js
- movie-server/models/Rent.js
> default value issue

- movie-server/jobs/rendModifications.js
RentModification file modified
> RentModification file modified

- movie-server/controller/RentController.js
> added 48 hours

- movie-server/jobs/rendModifications.js
utc added in rentModications.js
> utc added in rentModications.js

- movie-server/controller/RentController.js
- movie-server/jobs/rendModifications.js
> UTC changed

- movie-server/controller/MovieController.js
> movie controller setup

- movie-client/package-lock.json
- movie-server/controller/RentController.js
> rent list updated

- movie-client/src/app/services/movie.service.ts
fixed sorting in case of movie listing
> fixed sorting in case of movie listing

- movie-server/controller/RentController.js
> rent method updated

- movie-client/src/app/pages/movies/movies.component.html
deleted movie does not show in client side fixed
> deleted movie does not show in client side fixed

- movie-server/controller/RentController.js
> console removing

- movie-server/controller/WishlistController.js
deleted movie not added to wishlist fixed
> deleted movie not added to wishlist fixed

- movie-client/src/app/pages/movies/movies.component.ts
> sorting fixed in movie list

- movie-server/controller/RentController.js
> is movie available

- movie-server/controller/RentController.js
> message changes

- movie-server/controller/MovieController.js
> message changed again

- movie-client/src/app/pages/notfound/notfound.component.html
> 404 updated

- movie-server/controller/WishlistController.js
wishlist fixed unchecking wishlist was not working
> wishlist fixed unchecking wishlist was not working

- movie-server/controller/MovieController.js
- movie-server/package-lock.json
> genre issues

- movie-server/controller/MovieController.js
> genre issue

- movie-server/controller/MovieController.js
> checking genre

- movie-client/src/app/pages/movies/movies.component.html
add genere into movie manage genre wise movie list in client UI fixed
> add genere into movie manage genre wise movie list in client UI fixed

- movie-server/controller/MovieController.js
> Genre added in movie listing

- movie-server/controller/MovieController.js
> query modification

- movie-server/controller/MovieController.js
> rentData removed

- movie-client/src/app/pages/movies/movies.component.html
- movie-client/src/app/pages/movies/movies.component.ts
This reverts commit 35ae41553a24fbdf95a6f7dd055ed496c7b3e03c.
> Revert "Dev - updated genre (#238)"

- movie-server/controller/MovieController.js
> query modification in movie

- movie-server/controller/MovieController.js
missing trailerurl, thumbnail,year added
> missing trailerurl, thumbnail,year added

- movie-server/controller/UserController.js
> user updated

- movie-server/controller/MovieController.js
> working rent flags

- movie-server/controller/MovieController.js
Fix: Movie showing in user section upon deleting from admin
> Fix: Movie showing in user section upon deleting from admin

- movie-client/src/app/pages/wishlist/wishlist.component.html
button class changed in wishlist delete modal
> button class changed in wishlist delete modal
